# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19
        cache-dependency-path: ~/.proglog
      
    - name: make init
      run: make init
    
    # - name: Install cfssl
    #   uses: jaxxstorm/action-install-gh-release@v1.10.0
    #   with: # Grab the latest version
    #     repo: cloudflare/cfssl
    #     tag: cfssl_1.6.4_linux_amd64

    - name: Install dependecies 
      run: |
        go version
        go install github.com/cloudflare/cfssl/cmd/...@latest
        make init
        make gencert

    - name: Test
      run: make test
